import 'package:flutter_enterprise_app/features/product/domain/entities/product.dart';
import 'package:hive/hive.dart';

part 'product_model.g.dart'; // Must be generated by build_runner

@HiveType(typeId: 0) // For Hive persistence [cite: 30]
class ProductModel extends Product {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final double price;

  @HiveField(3)
  final String description;

  @HiveField(4)
  final String category;

  @HiveField(5)
  final String image;

  const ProductModel({
    required this.id,
    required this.title,
    required this.price,
    required this.description,
    required this.category,
    required this.image,
  }) : super(
    id: id,
    title: title,
    price: price,
    description: description,
    category: category,
    image: image,
  );

  // Parses JSON from API [cite: 12]
  factory ProductModel.fromJson(Map<String, dynamic> json) {
    return ProductModel(
      id: json['id'],
      title: json['title'],
      price: (json['price'] as num).toDouble(),
      description: json['description'],
      category: json['category'],
      image: json['image'],
    );
  }
}