import 'package:flutter_enterprise_app/features/cart/domain/entities/cart_item.dart';
import 'package:flutter_enterprise_app/features/product/data/models/product_model.dart';
import 'package:hive/hive.dart';

part 'cart_item_model.g.dart'; // Must be generated by build_runner

@HiveType(typeId: 1) // For Hive persistence [cite: 31]
class CartItemModel extends CartItem {
  @HiveField(0)
  final ProductModel product;

  @HiveField(1)
  final int quantity;

  const CartItemModel({
    required this.product,
    required this.quantity,
  }) : super(product: product, quantity: quantity);

  @override
  CartItemModel copyWith({int? quantity}) {
    return CartItemModel(
      product: product,
      quantity: quantity ?? this.quantity,
    );
  }
}